version: '2'

services:

  suricata:
    build: ./${OS_SURICATA}/Dockerfile/
    container_name: suricata
    cap_add:
      - NET_ADMIN
    network_mode: "host"
    volumes:
      - /var/log/suricata:/var/log/suricata
      - ./rules/suricata.rules:/var/lib/suricata/rules/suricata.rules
    entrypoint: /tmp/docker-entrypoint.sh
